name: GitHub Actions
run-name: Using GitHub Actions 🚀
on:
  push:
    branches:
      - "main"
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - run: echo "Start runnning unit test on Github Actions"
      - uses: actions/checkout@v2
      - name: Setup on Node.JS ${{matrix.node-version}}
        uses: actions/setup-node@v1
        with: 
          node-version: ${{matrix.node-version}}
      - name: Installation
        run: npm ci
      - name: Testing
        run: npm test
      - run: echo "🍏 This job's status is ${{ job.status }}."
  push-to-dockerhub:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - run: echo "Pushing code to DockerHub"
      - uses: actions/checkout@v2
      - name: docker login
        env:
          DOCKER_USER: ${{secrets.DOCKERHUB_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKERHUB_PASSWORD}}
        run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag latest
      - name: docker push
        run: docker push ${{secrets.DOCKERHUB_USER}}/simple-api-with-docker_web